#!/usr/bin/env ruby

require 'net/http'
require 'uri'
require "rexml/document"
require 'byebug'

include REXML

class RSSDownloader
  class FeedConfig
    attr_accessor :name,
                  :feed_url,
                  :element_xpath,
                  :title_xpath,
                  :title_matcher,
                  :download_xpath,
                  :download_dir

    def initialize feed
      @name             = feed['name']
      @feed_url         = feed['feed_url']
      @element_xpath    = feed['element_xpath']
      @title_xpath      = feed['title_xpath']
      @title_matcher    = feed['title_matcher']
      @download_xpath   = feed['download_xpath']
      @download_dir     = feed['download_dir']
    end
  end

  def initialize
    @yaml  = YAML.load_file(get_config_file_path)
    @feeds = []
  end

  def parse
    @yaml['feeds'].each do |feed|
      @feeds.push(FeedConfig.new(feed))
    end
  end

  def run
    parse

    @feeds.each do |feed|
      feed_content = get_rss_content feed.feed_url
      feed_item_list = get_values feed_content, feed.element_xpath
      debugger
    end
  end

  def get_rss_content url
    Net::HTTP.get(URI.parse(url))
  end

  def get_config_file_path
    "#{Dir.home}/.rss-downloader/config.yml"
  end

  def get_values document, xpath
    xpath_document = Document.new document
    XPath.each(xpath_document, xpath) do |node|
      if node.is_a?(Attribute)
        def node.parent
          self.element
        end
      end
      puts node.text
    end
  end
end

@rss_downloader = RSSDownloader.new
@rss_downloader.run
