feeds:
  - name: 'My Sample RSS Feed 1'
    feed_url: 'http://www.mywebsite.com/rss/feed'
    xpath: '//item/link/text()'
    download_dir: '~/downloads/mywebsite/'
  - name: 'My Sample RSS Feed 2'
    feed_url: 'http://www.test.com/feed/123'
    xpath: '//links/records/url/text()'
    download_dir: '~/test.com.downloads/urls/'
  - name: 'My Sample RSS Feed 3'
    feed_url: 'http://www.myfeed.com/test/feed'
    xpath: '/tests/test/feed/item/text()'
    download_dir: '~/myfeed/watch_dir/'
