feeds:
  - name: 'My Sample RSS Feed 1'
    feed_url: 'http://www.mywebsite.com/rss/feed'
    element_xpath: '//item'
    title_xpath: 'title'
    title_matcher: 'test.*matcher'
    download_xpath: 'link'
    download_dir: '~/downloads/mywebsite/'

  - name: 'My Sample RSS Feed 2'
    feed_url: 'http://www.test.com/feed/123'
    element_xpath: '//links'
    title_xpath: 'title'
    title_matcher: 'match[12]3'
    download_xpath: '//links/records/url/text()'
    download_dir: '~/test.com.downloads/urls/'

  - name: 'My Sample RSS Feed 3'
    feed_url: 'http://www.myfeed.com/test/feed'
    element_xpath: '//tests/test'
    title_xpath: 'feed/title'
    title_matcher: 'match_[this|that]'
    download_xpath: 'feed/item'
    download_dir: '~/myfeed/watch_dir/'
